type improvements, export constant helpers
ammario/kalshi pull request #1
Opened 2023-04-14 14:09 UTC by cmoog

2023-04-15 19:43 UTC, cmoog commented
Looks like CI failure is due to missing secrets.

2023-04-17 02:05 UTC, ammario requested changes
Overall great changes!

2023-04-17 02:05 UTC, ammario commented on client.go
> +}
I avoided exporting a function like this because of the risk of float rounding errors leading to incorrect bot decisions. If a user needs a similar method they should implement it themselves and take responsibility for rounding and precision.

How about we internalize it since it's only used by String?

2023-04-17 02:52 UTC, cmoog commented on client.go
> +}
Agreed.

2023-04-17 03:27 UTC, ammario commented
`git apply` this and we're good for merge

```diff
diff --git a/portfolio_test.go b/portfolio_test.go
index 12c4507..8ecdfa0 100644
--- a/portfolio_test.go
+++ b/portfolio_test.go
@@ -71,7 +71,7 @@ func TestOrder(t *testing.T) {
 		t.Logf("created order: %+v", order)
 		require.True(t, order.ExpirationTime.After((time.Now())))
 		// Market order should execute immediately.
-		require.Equal(t, "executed", order.Status)
+		require.Equal(t, Executed, order.Status)
 		t.Run("Fills", func(t *testing.T) {
 			t.Skip("Doesn't seem to work?")
 			fills, err := client.Fills(ctx, FillsRequest{
@@ -140,7 +140,7 @@ func TestOrder(t *testing.T) {
 		t.Run("Cancel", func(t *testing.T) {
 			order, err := client.CancelOrder(ctx, order.OrderID)
 			require.NoError(t, err)
-			require.Equal(t, order.Status, "canceled")
+			require.Equal(t, Canceled, order.Status)
 		})
 	})
 }
```

2023-04-17 23:03 UTC, merged

2023-04-17 23:53 UTC, cmoog commented
Just realized this is needed to prevent panics when `(*CreateOrderRequest).String()` is invoked with a `nil` expiration time.
```diff
diff --git a/portfolio.go b/portfolio.go
index 1019307..b69bf88 100644
--- a/portfolio.go
+++ b/portfolio.go
@@ -55,9 +55,13 @@ func (c *CreateOrderRequest) String() string {
 	} else {
 		price = c.NoPrice
 	}
+	expire := "never"
+	if c.Expiration != nil {
+		expire = fmt.Sprintf("in %v", time.Until(c.Expiration.Time()))
+	}
 	return fmt.Sprintf(
-		"%v %v %v at %v cents, expires in %v, max cost is %v",
-		c.Action, c.Count, strings.ToUpper(string(c.Side)), price, time.Until(c.Expiration.Time()), c.BuyMaxCost,
+		"%v %v %v at %v, expires %s, max cost is %v",
+		c.Action, c.Count, strings.ToUpper(string(c.Side)), price, expire, c.BuyMaxCost,
 	)
 }
 

```

2023-04-19 16:02 UTC, ammario commented
https://github.com/ammario/kalshi/commit/cc94f31cf72abb8b99a473f0b24bd8f37728dac6